

insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('AC','Acre','Rio Branco','Norte','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('AL','Alagoas','Maceió','Nordeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('AM','Amazonas','Manaus','Norte','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('AP','Amapá','Macapá','Norte','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('BA','Bahia','Salvador','Nordeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('CE','Ceará','Fortaleza','Nordeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('DF','Distrito Federal','Brasília','Centro-Oeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('ES','Espírito Santo','Vitória','Sudeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('GO','Goiás','Goiânia','Centro-Oeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('MA','Maranhão','São Luís','Nordeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('MG','Minas Gerais','Belo Horizonte','Sudeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('MS','Mato Grosso do Sul','Campo Grande','Centro-Oeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('MT','Mato Grosso','Cuiabá','Centro-Oeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('PA','Pará','Belém','Norte','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('PB','Paraíba','João Pessoa','Nordeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('PE','Pernambuco','Recife','Nordeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('PI','Piauí','Teresina','Nordeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('PR','Paraná','Curitiba','Sul','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('RJ','Rio de Janeiro','Rio de Janeiro','Sudeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('RN','Rio Grande do Norte','Natal','Nordeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('RO','Rondônia','Porto Velho','Norte','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('RR','Roraima','Boa Vista','Norte','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('RS','Rio Grande do Sul','Porto Alegre','Sul','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('SC','Santa Catarina','Florianópolis','Sul','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('SE','Sergipe','Aracaju','Nordeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('SP','São Paulo','São Paulo','Sudeste','BR');
insert into EstadoRegiao (uf, estado, capital, regiao, pais) values('TO','Tocantins','Palmas','Norte','BR');
select * from EstadoRegiao;
